@startuml

package "apigateway" {
    package "app" {
        package "middlewares" {
            class Cache {
                +method1()
                +method2()
            }

            class FunctionsJWT {
                +method1()
                +method2()
            }

            class RateLimit {
                +method1()
                +method2()
            }

            class VerifyTokenRoute {
                +method1()
                +method2()
            }
        }

        package "routes" {
            class Auth {
                +method1()
                +method2()
            }

            class Users {
                +method1()
                +method2()
            }
        }
    }
}

@enduml
