version: '3.8'

services:
  api_gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "4699:8000"
    environment:
      - REDIS_URL=redis://192.168.0.12:6379/0  # Apuntar a Redis en el host local

  api_practicas:
    build:
      context: ./practicas
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://192.168.0.12:27017/incripciondb  # Apuntar a MongoDB en el host local

  api_files:
    build:
      context: ./files
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - MONGO_URL=mongodb://192.168.0.12:27017/filesdb  # Apuntar a MongoDB en el host local

  api_empresas:
    build:
      context: ./empresas
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - MONGO_URL=mongodb://192.168.0.12:27017/empresasdb  # Apuntar a MongoDB en el host local

  api_notificaciones:
    build:
      context: ./notificaciones
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - MONGO_URL=mongodb://192.168.0.12:27017/notificacionesdb  # Apuntar a MongoDB en el host local

  api_profesores:
    build:
      context: ./profesores
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    environment:
      - MONGO_URL=mongodb://192.168.0.12:27017/profesoresdb  # Apuntar a MongoDB en el host local

volumes:
  mongo_data:
